comienzo/urls.py
from django.urls import path
from comienzo.views import comienzo,acerca_de_mi,template1

app_name="comienzo"

urlpatterns = [
   path("",comienzo,name="inicio"),
   path("acerca-de-mi/",acerca_de_mi,name="acerca_de_mi"),
   path("template1/",template1,name="template1"),

]

habitacion/urls.py
from django.urls import path
from habitacion import views

app_name="habitacion"

urlpatterns = [
    path("buscar-acolchados/",views.buscar_acolchados,name="buscar_acolchados"),
    path("crear-acolchados/",views.crear_acolchados,name="crear_acolchados"),
    path("ver-acolchados/<int:pk>/",views.VerAcolchados.as_view(),name="ver_acolchados"),
    path("eliminar-acolchados/<int:id>/",views.eliminar_acolchados,name="eliminar_acolchados"),
    path("listado-sabanas/",views.listado_sabanas,name="listado_sabanas"),
    path("editar-acolchados/<int:pk>/",views.EditarAcolchados.as_view(),name="editar_acolchados"),
    path("sabana/crear/",views.CrearSabana.as_view(),name="crear_sabana"),
    path("sabana/<int:pk>/",views.VerSabana.as_view(),name="ver_sabana"),
    path("sabana/<int:pk>/editar",views.EditarSabana.as_view(),name="editar_sabana"),
    path("sabana/<int:pk>/eliminar",views.EliminarSabana.as_view(),name="eliminar_sabana"),
    path("frazada/crear/",views.CrearFrazada.as_view(),name="crear_frazada"),
    path("listado-frazadas/",views.listado_frazadas,name="listado_frazadas"),
    path("frazada/<int:pk>/",views.VerFrazada.as_view(),name="ver_frazada"),
    path("frazada/<int:pk>/editar",views.EditarFrazada.as_view(),name="editar_frazada"),
    path("frazada/<int:pk>/eliminar",views.EliminarFrazada.as_view(),name="eliminar_frazada"),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("comienzo.urls")),
    path("habitacion/",include("habitacion.urls")),
    path("usuarios/",include("usuarios.urls")),
    

]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

habitacion/models.py
from django.db import models

class Acolchados(models.Model):
    TAMANIO_VALUES = [
        ("twin", "Twin"),
        ("queen", "Queen"),
        ("king", "King")
        ]
    tamanio=models.CharField(max_length=10,choices=TAMANIO_VALUES,verbose_name="Tamaño")
    
    color=models.CharField(max_length=20,verbose_name="Color")
    composicion=models.CharField(max_length=20,verbose_name="Composición")
    fecha_fabricacion=models.DateField(blank=True,null=True,verbose_name="Fecha de Fabricación")
    imagen_acolchado=models.ImageField(upload_to="imagenes",blank=True,null=True)
    
    
    def __str__(self):
        return f"{self.tamanio} {self.color}"


class Sabana(models.Model):
    TAMANIO_VALUES = [
        ("twin", "Twin"),
        ("queen", "Queen"),
        ("king", "King")
        ]
    tamanio=models.CharField(max_length=10,choices=TAMANIO_VALUES,verbose_name="Tamaño")
    
    color=models.CharField(max_length=20,verbose_name="Color")
    composicion=models.CharField(max_length=20,verbose_name="Composición")
    hilos=models.IntegerField(verbose_name="Hilos")
    fecha_fabricacion=models.DateField(blank=True,null=True,verbose_name="Fecha de Fabricación")
    imagen_sabana= models.ImageField(upload_to="imagenes",blank=True,null=True)
    
    def __str__(self):
        return f"{self.composicion} {self.color}"
    
class Frazada(models.Model):
    TAMANIO_VALUES = [
        ("twin", "Twin"),
        ("queen", "Queen"),
        ("king", "King")
        ]
    ESTILO_VALUES = [
        ("liso", "Liso"),
        ("rústico", "Rústico"),
        ("estampado", "Estampado")
        ]
    tamanio=models.CharField(max_length=10,choices=TAMANIO_VALUES,verbose_name="Tamaño")
    
    color=models.CharField(max_length=20,verbose_name="Color")
    estilo=models.CharField(max_length=10,choices=ESTILO_VALUES,verbose_name="Estilo")
    fecha_fabricacion=models.DateField(blank=True,null=True,verbose_name="Fecha de Fabricación")
    imagen_frazada=models.ImageField(upload_to="imagenes",blank=True,null=True)
    
    def __str__(self):
        return f"{self.color} {self.estilo}"

habitacion/forms.py
from django import forms 

class CrearFormulario(forms.Form):
    TAMAÑO_CHOICES = [
        ("twin", "Twin"),
        ("queen", "Queen"),
        ("king", "King")
        ]

    tamanio=forms.ChoiceField(choices=TAMAÑO_CHOICES,label="Tamaño")
    color=forms.CharField(max_length=20)
    composicion=forms.CharField(max_length=20)
    fecha_fabricacion=forms.DateField()
    imagen_acolchado=forms.ImageField(required=False)

class BuscarFormulario(forms.Form):
    color=forms.CharField(max_length=20,required=False)
    composicion=forms.CharField(max_length=20,required=False)
    
class BuscarFormularioFrazada(forms.Form):
        color=forms.CharField(max_length=20,required=False)



class EditarFormulario(forms.Form):
    TAMAÑO_CHOICES = [
        ("twin", "Twin"),
        ("queen", "Queen"),
        ("king", "King")
        ]

    tamanio=forms.ChoiceField(choices=TAMAÑO_CHOICES,label="Tamaño")
    color=forms.CharField(max_length=20)
    composicion=forms.CharField(max_length=20)
    fecha_fabricacion=forms.DateField()
    imagen_acolchado=forms.ImageField(required=False)

habitacion/views.py
from django.http import HttpResponse
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from habitacion.models import Sabana,Frazada,Acolchados
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template import Template,Context,loader
from django.shortcuts import render,redirect
from habitacion.forms import CrearFormulario, BuscarFormulario,EditarFormulario,BuscarFormularioFrazada
from django.contrib.auth.decorators import login_required

#ACOLCHADO
def buscar_acolchados(request):
    formulario=BuscarFormulario(request.GET)
    if formulario.is_valid():
        color=formulario.cleaned_data.get("color")
        composicion=formulario.cleaned_data.get("composicion")
        acolchados=Acolchados.objects.filter(color__icontains=color,composicion__icontains=composicion)
    return render(request,"habitacion/buscar_acolchados.html", {"acolchados":acolchados,"form":formulario})
    
def crear_acolchados(request):
    formulario=CrearFormulario()
    if request.method=="POST":
        formulario= CrearFormulario(request.POST,request.FILES)
        if formulario.is_valid():
            data=formulario.cleaned_data
            acolchados=Acolchados(tamanio=data.get("tamanio"),color=data.get("color"),composicion=data.get("composicion"),fecha_fabricacion=data.get("fecha_fabricacion"),imagen_acolchado=data.get("imagen_acolchado"))
            acolchados.save()
            return redirect("habitacion:buscar_acolchados")
            
    return render(request,"habitacion/crear_acolchados.html", {"form":formulario})

class VerAcolchados(DetailView):
    model= Acolchados
    template_name="habitacion/ver_acolchados.html"
    context_object_name="acolchado"


@login_required
def eliminar_acolchados(request,id):
    acolchados=Acolchados.objects.get(id=id)
    acolchados.delete()
    return redirect("habitacion:buscar_acolchados")

class EditarAcolchados(LoginRequiredMixin,UpdateView):
    model = Acolchados
    template_name = "habitacion/editar_acolchados.html"
    success_url=reverse_lazy("habitacion:buscar_acolchados")
    fields=["tamanio","color","composicion","fecha_fabricacion","imagen_acolchado"]
    context_object_name="acolchado"


#################################################################################3

#SABANA

class CrearSabana(CreateView):
    model = Sabana
    template_name = "habitacion/crear_sabana.html"
    success_url= reverse_lazy("habitacion:listado_sabanas")
    fields=["tamanio","color","composicion","hilos","fecha_fabricacion","imagen_sabana"]
    
    
def listado_sabanas(request):
    formulario=BuscarFormulario(request.GET)
    if formulario.is_valid():
        color=formulario.cleaned_data.get("color")
        composicion=formulario.cleaned_data.get("composicion")
        sabanas=Sabana.objects.filter(color__icontains=color,composicion__icontains=composicion)
    return render(request,"habitacion/listado_sabanas.html", {"sabanas":sabanas,"form":formulario})


class VerSabana(DetailView):
    model = Sabana
    template_name = "habitacion/ver_sabana.html"

class EditarSabana(LoginRequiredMixin,UpdateView):
    model = Sabana
    template_name = "habitacion/editar_sabana.html"
    success_url=reverse_lazy("habitacion:listado_sabanas")
    fields=["tamanio","color","composicion","hilos","fecha_fabricacion","imagen_sabana"]

class EliminarSabana(LoginRequiredMixin,DeleteView):
    model = Sabana
    template_name = "habitacion/eliminar_sabana.html"
    success_url=reverse_lazy("habitacion:listado_sabanas")

#######################################################################################3

#FRAZADA
class CrearFrazada(CreateView):
    model = Frazada
    template_name = "habitacion/crear_frazada.html"
    success_url= reverse_lazy("habitacion:listado_frazadas")
    fields=["tamanio","color","estilo","fecha_fabricacion","imagen_frazada"]
    
def listado_frazadas(request):
    formulario=BuscarFormularioFrazada(request.GET)
    frazadas=[]
    if formulario.is_valid():
        color=formulario.cleaned_data.get("color")
        frazadas=Frazada.objects.filter(color__icontains=color)
    return render(request,"habitacion/listado_frazadas.html", {"frazadas":frazadas,"form":formulario})


class VerFrazada(DetailView):
    model = Frazada
    template_name = "habitacion/ver_frazada.html"

class EditarFrazada(LoginRequiredMixin,UpdateView):
    model = Frazada
    template_name = "habitacion/editar_frazada.html"
    success_url=reverse_lazy("habitacion:listado_frazadas")
    fields=["tamanio","color","estilo","fecha_fabricacion","imagen_frazada"]

class EliminarFrazada(LoginRequiredMixin,DeleteView):
    model = Frazada
    template_name = "habitacion/eliminar_frazada.html"
    success_url=reverse_lazy("habitacion:listado_frazadas")

habitacion/templates/habitacion/buscar_acolchados.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Buscar acolchados
{% endblock title_head %}

{% block h1_header %}
Buscar acolchados
{% endblock h1_header %}

{% block main %}
<form action={% url "habitacion:buscar_acolchados" %}>
{{form}}
<input type="submit">

</form>
<a href={% url "habitacion:crear_acolchados"%} class="btn btn-info">Crear nuevo acolchado</a>
{% if acolchados %}
<ul>
    {% for acolchado in acolchados %}
    <li>{{acolchado}}
        ||<a href={% url "habitacion:ver_acolchados" acolchado.id %}>Información completa</a>
        ||<a href={% url "habitacion:editar_acolchados" acolchado.id %}>Editar</a>
        ||<a href={% url "habitacion:eliminar_acolchados" acolchado.id %}>Eliminar</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No hay acolchados cargados en esta página</p>
{% endif %}

{% endblock main %}

habitacion/templates/habitacion/crear_acolchados.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Crear acolchados
{% endblock title_head %}

{% block h1_header %}
Crear acolchados
{% endblock h1_header %}

{% block main %}
<form action={% url "habitacion:crear_acolchados"%} method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <input type="submit" value="Crear">


</form>
{% endblock main %}

habitacion/templates/habitacion/crear_frazada.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Crear frazadas
{% endblock title_head %}

{% block h1_header %}
Crear frazadas
{% endblock h1_header %}

{% block main %}
<form action={% url "habitacion:crear_frazada"%} method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form}}
    </table> 

    <input type="submit" value="Crear">

</form>
{% endblock main %}

habitacion/templates/habitacion/crear_sabana.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Crear sabanas
{% endblock title_head %}

{% block h1_header %}
Crear sabanas
{% endblock h1_header %}

{% block main %}
<form action={% url "habitacion:crear_sabana"%} method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<table>
    {{form}}
    
</table>

    <input type="submit" value="Crear">

</form>
{% endblock main %}

habitacion/templates/habitacion/editar_acolchados.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Editar acolchados
{% endblock title_head %}

{% block h1_header %}
Editar {{acolchado}}
{% endblock h1_header %}

{% block main %}
<form action={% url "habitacion:editar_acolchados" acolchado.pk%} method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<table>
    {{form}}
    
</table>

    <input type="submit" value="Enviar">

</form>
{% endblock main %}

habitacion/templates/habitacion/editar_frazada.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Editar Frazadas
{% endblock title_head %}

{% block h1_header %}
Editar Frazada {{frazada.tamanio}} {{frazada.color}}
{% endblock h1_header %}

{% block main %}
<form action={% url "habitacion:editar_frazada" frazada.id%} method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<table>
    {{form}}
    
</table>

    <input type="submit" value="Editar">

</form>
{% endblock main %}

habitacion/templates/habitacion/editar_sabana.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Editar Sábanas
{% endblock title_head %}

{% block h1_header %}
Editar Sábana {{sabana.composicion}} {{sabana.color}}
{% endblock h1_header %}

{% block main %}
<form action={% url "habitacion:editar_sabana" sabana.id%} method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
<table>
    {{form}}
    
</table>

    <input type="submit" value="Editar">

</form>
{% endblock main %}

habitacion/templates/habitacion/eliminar_frazada.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Eliminar Frazadas
{% endblock title_head %}

{% block h1_header %}
Eliminar Frazada {{frazada.tamanio}} {{frazada.color}}
{% endblock h1_header %}

{% block main %}
<form action={% url "habitacion:eliminar_frazada" frazada.id%} method="POST">
    {% csrf_token %}

<p>Está seguro de eliminar esta frazada {{frazada}}?</p>
    <input type="submit" value="Confirmar">

</form>

<table>
    <a href={% url "habitacion:listado_frazadas" %}>Volver al listado</a>
</table>

{% endblock main %}

habitacion/templates/habitacion/eliminar_sabana.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Eliminar Sábanas
{% endblock title_head %}

{% block h1_header %}
Eliminar Sábana {{sabana.composicion}} {{sabana.color}}
{% endblock h1_header %}

{% block main %}
<form action={% url "habitacion:eliminar_sabana" sabana.id%} method="POST" >
    {% csrf_token %}

<p>Está seguro de eliminar esta sábana {{sabana}}?</p>
    <input type="submit" value="Confirmar">

</form>

<table>
    <a href={% url "habitacion:listado_frazadas" %}>Volver al listado</a>
</table>

{% endblock main %}

habitacion/templates/habitacion/listado_frazadas.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Listado Frazadas
{% endblock title_head %}

{% block h1_header %}
Listado frazadas
{% endblock h1_header %}

{% block main %}

<form action={% url "habitacion:listado_frazadas" %}>
    {{form}}
    <input type="submit">
    
</form>

<a href={% url "habitacion:crear_frazada"%} class="btn btn-info">Crear nueva frazada</a>
{% if frazadas %}
<ul>
    {% for frazada in frazadas %}
    <li>{{frazada}}
        |<a href={% url "habitacion:ver_frazada" frazada.id %}>Información completa</a>
        ||<a href={% url "habitacion:editar_frazada" frazada.id %}>Editar</a>
        ||<a href={% url "habitacion:eliminar_frazada" frazada.id %}>Eliminar</a> 
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No hay frazadas cargadas en esta página</p>
{% endif %}

{% endblock main %}

habitacion/templates/habitacion/listado_sabanas.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Listado Sábanas
{% endblock title_head %}

{% block h1_header %}
Listado sábanas
{% endblock h1_header %}

{% block main %}
<form action={% url "habitacion:listado_sabanas" %}>
    {{form}}
    <input type="submit">
    
</form>
    
<a href={% url "habitacion:crear_sabana"%} class="btn btn-info">Crear nueva sábana</a>
{% if sabanas %}
<ul>
    {% for sabana in sabanas %}
    <li>{{sabana}}
        |<a href={% url "habitacion:ver_sabana" sabana.id %}>Información completa</a>
        ||<a href={% url "habitacion:editar_sabana" sabana.id %}>Editar</a>
        ||<a href={% url "habitacion:eliminar_sabana" sabana.id %}>Eliminar</a> 
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No hay sabanas cargadas en esta página</p>
{% endif %}

{% endblock main %}

habitacion/templates/habitacion/ver_acolchados.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Visualizar acolchados
{% endblock title_head %}

{% block h1_header %}
Visualizar acolchados
{% endblock h1_header %}

{% block main %}

<ul>
    <li>
        {{acolchado.tamanio}}

    </li>
    <li>
        {{acolchado.color}}
    </li>
    <li>
        {{acolchado.composicion}}
    </li>
    <li>
        {{acolchado.fecha_fabricacion}}
    </li>
    <li>
        {% if acolchado.imagen_acolchado %}
        <img src="{{ acolchado.imagen_acolchado.url }}" alt="Imagen de acolchado" style="max-width: 200px;">
        {% else %}
        <p>No hay una imagen disponible</p>
        {% endif %}

    </li>
        
</ul>

<ul>
    <table>
        <a href={% url "habitacion:buscar_acolchados" %}>Volver al listado</a>
    </table>
</ul>



{% endblock main %}

habitacion/templates/habitacion/ver_frazada.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Visualizar frazadas
{% endblock title_head %}

{% block h1_header %}
Visualizar frazadas
{% endblock h1_header %}

{% block main %}

<ul>


    <li>
        tamaño={{frazada.tamanio}}

    </li>
    <li>
        color={{frazada.color}}
    </li>
    <li>
        
        estilo={{frazada.estilo}}
    
  
    </li>
    <li>

        fecha={{frazada.fecha_fabricacion}}
    </li>
    <li>
        {% if frazada.imagen_frazada %}
        <img src="{{ frazada.imagen_frazada.url }}" alt="Imagen de frazada" style="max-width: 200px;">
        {% else %}
        <p>No hay una imagen disponible</p>
        {% endif %}
    </li>
    
</ul>

<ul>
    <table>
        <a href={% url "habitacion:listado_frazadas" %}>Volver al listado</a>
    </table>
</ul>



{% endblock main %}

habitacion/templates/habitacion/ver_sabana.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Visualizar sábanas
{% endblock title_head %}

{% block h1_header %}
Visualizar sábanas
{% endblock h1_header %}

{% block main %}



<ul>


    <li>
        tamaño={{sabana.tamanio}}

    </li>
    <li>
        color={{sabana.color}}
    </li>
    <li>
        
        composicion={{sabana.composicion}}
    
    <li>
        hilos={{sabana.hilos}}

    </li>
    <li>

        fecha={{sabana.fecha_fabricacion}}
    </li>
    <li>
        {% if sabana.imagen_sabana %}
        <img src="{{ sabana.imagen_sabana.url }}" alt="Imagen de sabana" style="max-width: 200px;">
        {% else %}
        <p>No hay una imagen disponible</p>
        {% endif %}
    </li>
    
</ul>

<ul>
    <table>
        <a href={% url "habitacion:listado_sabanas" %}>Volver al listado</a>
    </table>
</ul>



{% endblock main %}