comienzo/urls.py
from django.urls import path
from comienzo.views import comienzo,acerca_de_mi,template1

app_name="comienzo"

urlpatterns = [
   path("",comienzo,name="inicio"),
   path("acerca-de-mi/",acerca_de_mi,name="acerca_de_mi"),
   path("template1/",template1,name="template1"),

]

habitacion/urls.py
from django.urls import path
from habitacion import views

app_name="habitacion"

urlpatterns = [
    path("buscar-acolchados/",views.buscar_acolchados,name="buscar_acolchados"),
    path("crear-acolchados/",views.crear_acolchados,name="crear_acolchados"),
    path("ver-acolchados/<int:pk>/",views.VerAcolchados.as_view(),name="ver_acolchados"),
    path("eliminar-acolchados/<int:id>/",views.eliminar_acolchados,name="eliminar_acolchados"),
    path("listado-sabanas/",views.listado_sabanas,name="listado_sabanas"),
    path("editar-acolchados/<int:pk>/",views.EditarAcolchados.as_view(),name="editar_acolchados"),
    path("sabana/crear/",views.CrearSabana.as_view(),name="crear_sabana"),
    path("sabana/<int:pk>/",views.VerSabana.as_view(),name="ver_sabana"),
    path("sabana/<int:pk>/editar",views.EditarSabana.as_view(),name="editar_sabana"),
    path("sabana/<int:pk>/eliminar",views.EliminarSabana.as_view(),name="eliminar_sabana"),
    path("frazada/crear/",views.CrearFrazada.as_view(),name="crear_frazada"),
    path("listado-frazadas/",views.listado_frazadas,name="listado_frazadas"),
    path("frazada/<int:pk>/",views.VerFrazada.as_view(),name="ver_frazada"),
    path("frazada/<int:pk>/editar",views.EditarFrazada.as_view(),name="editar_frazada"),
    path("frazada/<int:pk>/eliminar",views.EliminarFrazada.as_view(),name="eliminar_frazada"),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("comienzo.urls")),
    path("habitacion/",include("habitacion.urls")),
    path("usuarios/",include("usuarios.urls")),
    

]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

comienzo/models.py
from django.db import models

comienzo/forms.py
from django import forms 

comienzo/views.py
from django.shortcuts import render

def comienzo(request):
    return render(request,"comienzo/index.html")

def template1(request):
     return render(request,"template1.html")

def acerca_de_mi(request):
    return render(request,"comienzo/acerca_de_mi.html")

comienzo/templates/comienzo/acerca_de_mi.html
{% extends "base.html" %}
{% load static %}

{% block title_head %}
Acerca de mí
{% endblock title_head %}

{% block h1_header %} Acerca de mí{% endblock h1_header %}

{% block main %}

<ul>
    <li>Soy Lourdes!</li>
    <li>Tengo 26 años</li>
    <li>Vivo en Argentina</li>
    <li>Soy Contadora Pública, recibida en la Facultad de Ciencias Económicas de la Universidad de Buenos Aires</li>
    <li>Actualmente trabajo en un estudio contable</li>
    <li>Tengo dos mascotas, una perrita y una gatita</li>
    <li>Soy una persona curiosa, con muchas ganas de aprender cosas nuevas</li>
    <img src="{% static 'assets/image.png' %}" alt="Imagen" height= "500px">
</ul>
{% endblock main %}

comienzo/templates/comienzo/crear_acolchados.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Crear acolchados
{% endblock title_head %}

{% block h1_header %}
Crear acolchados
{% endblock h1_header %}

{% block main %}
<form action={% url "comienzo:crear_acolchados"%} method="POST">
    {% csrf_token %}
<table>
    {{form}}
    
</table>

    <input type="submit" value="Enviar">

</form>
{% endblock main %}

comienzo/templates/comienzo/index.html
{% extends "base.html" %}

{% block title_head %}
Inicio
{% endblock title_head %}

{% block h1_header %}
Bienvenidos a la página
{% endblock h1_header %}