comienzo/urls.py
from django.urls import path
from comienzo.views import comienzo,acerca_de_mi,template1

app_name="comienzo"

urlpatterns = [
   path("",comienzo,name="inicio"),
   path("acerca-de-mi/",acerca_de_mi,name="acerca_de_mi"),
   path("template1/",template1,name="template1"),

]

habitacion/urls.py
from django.urls import path
from habitacion import views

app_name="habitacion"

urlpatterns = [
    path("buscar-acolchados/",views.buscar_acolchados,name="buscar_acolchados"),
    path("crear-acolchados/",views.crear_acolchados,name="crear_acolchados"),
    path("ver-acolchados/<int:pk>/",views.VerAcolchados.as_view(),name="ver_acolchados"),
    path("eliminar-acolchados/<int:id>/",views.eliminar_acolchados,name="eliminar_acolchados"),
    path("listado-sabanas/",views.listado_sabanas,name="listado_sabanas"),
    path("editar-acolchados/<int:pk>/",views.EditarAcolchados.as_view(),name="editar_acolchados"),
    path("sabana/crear/",views.CrearSabana.as_view(),name="crear_sabana"),
    path("sabana/<int:pk>/",views.VerSabana.as_view(),name="ver_sabana"),
    path("sabana/<int:pk>/editar",views.EditarSabana.as_view(),name="editar_sabana"),
    path("sabana/<int:pk>/eliminar",views.EliminarSabana.as_view(),name="eliminar_sabana"),
    path("frazada/crear/",views.CrearFrazada.as_view(),name="crear_frazada"),
    path("listado-frazadas/",views.listado_frazadas,name="listado_frazadas"),
    path("frazada/<int:pk>/",views.VerFrazada.as_view(),name="ver_frazada"),
    path("frazada/<int:pk>/editar",views.EditarFrazada.as_view(),name="editar_frazada"),
    path("frazada/<int:pk>/eliminar",views.EliminarFrazada.as_view(),name="eliminar_frazada"),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("comienzo.urls")),
    path("habitacion/",include("habitacion.urls")),
    path("usuarios/",include("usuarios.urls")),
    

]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from usuarios import views
from django.contrib.auth.views import LogoutView

app_name="usuarios"

urlpatterns = [
    path("acceso/",views.acceso,name="acceso"),
    path("registro/",views.registro,name="registro"),
    path("perfil/ver",views.ver_perfil,name="ver_perfil"),
    path("perfil/modificar",views.modificar_perfil,name="modificar_perfil"),
    path("perfil/modificar/contrasenia",views.ModificarContrasenia.as_view(),name="modificar_contrasenia"),
    path("salir/",LogoutView.as_view(template_name="usuarios/salir.html"),name="salir"),
    
    
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "css/styles.css" %} rel="stylesheet" />
        <title>
            {% block title_head %}
            Bienvenidos!
            
            {% endblock title_head %}
        </title>


    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href={% url "comienzo:inicio" %}>Inicio</a>
                <a class="navbar-brand" href={% url "comienzo:template1" %}>Objetivo</a>
                <a class="navbar-brand" href={% url "habitacion:buscar_acolchados" %}>Acolchados</a>
                <a class="navbar-brand" href={% url "habitacion:listado_sabanas" %}>Sábanas</a>
                <a class="navbar-brand" href={% url "habitacion:listado_frazadas" %}>Frazadas</a>
                <a class="navbar-brand" href={% url "comienzo:acerca_de_mi" %}>Acerca de mí</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        {% if request.user.is_authenticated %}
                        <a class="navbar-brand" href={% url "usuarios:ver_perfil" %}>
                            {% if request.user.datosextra.avatar %}
                            <img src={{request.user.datosextra.avatar.url}} alt="" height="30 px">
                            {% endif %}
                            {{request.user.username}}</a>
                        <form action={% url "usuarios:salir" %} method="post">

                            {% csrf_token %}
                            <input type="submit" class="btn btn-secondary"value="Cerrar sesión">

                        </form>

                        {% else %}
                        
                        <li class="nav-item"><a class="nav-link btn btn-primary" href={% url "usuarios:acceso" %}>Ingresar a la página</a></li>
                        {% comment %} <li class="nav-item"><a class="nav-link btn btn-info" href={% url "usuarios:ver_perfil" %}>Ver Perfil</a></li> {% endcomment %}
                        <li class="nav-item"><a class="nav-link btn btn-danger" href={% url "usuarios:registro" %}>Registarse</a></li>
                        {% endif %}
                        
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="masthead text-center text-white">
            <div class="masthead-content">
            <!-- Page heading-->
                             <h1 class="mb-5">
                                 {% block h1_header %}Soy el base{% endblock h1_header %}
                                </h1>
            </div>
            <div class="bg-circle-1 bg-circle"></div>
            <div class="bg-circle-2 bg-circle"></div>
            <div class="bg-circle-3 bg-circle"></div>
            <div class="bg-circle-4 bg-circle"></div>
        </header>
        <main>
            {% block main %}{% endblock main %}
        </main>
        <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Your Website 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script> {% endcomment %}
        <!-- Core theme JS-->
        {% comment %} <script src="js/scripts.js"></script> {% endcomment %}
        
        
    </body>
</html>

templates/template1.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Objetivo
{% endblock title_head %}

{% block h1_header %} Crearemos artículos de blanquería{% endblock h1_header %}

{% block main %}
<div style="text-align: center;">
    <img src="{% static 'assets/Acolchado1.PNG' %}" alt="Imagen" height= "350px">
</div>

{% endblock main %}