comienzo/urls.py
from django.urls import path
from comienzo.views import comienzo,acerca_de_mi,template1

app_name="comienzo"

urlpatterns = [
   path("",comienzo,name="inicio"),
   path("acerca-de-mi/",acerca_de_mi,name="acerca_de_mi"),
   path("template1/",template1,name="template1"),

]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("comienzo.urls")),
    path("habitacion/",include("habitacion.urls")),
    path("usuarios/",include("usuarios.urls")),
    

]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from usuarios import views
from django.contrib.auth.views import LogoutView

app_name="usuarios"

urlpatterns = [
    path("acceso/",views.acceso,name="acceso"),
    path("registro/",views.registro,name="registro"),
    path("perfil/ver",views.ver_perfil,name="ver_perfil"),
    path("perfil/modificar",views.modificar_perfil,name="modificar_perfil"),
    path("perfil/modificar/contrasenia",views.ModificarContrasenia.as_view(),name="modificar_contrasenia"),
    path("salir/",LogoutView.as_view(template_name="usuarios/salir.html"),name="salir"),
    
    
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

class DatosExtra(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    avatar=models.ImageField(upload_to="avatares",blank=True,null=True)
    fecha_de_nacimiento = models.DateField(blank=True, null=True)
    

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm
from django.contrib.auth.models import User

class FormularioDeRegistro(UserCreationForm):
    username=forms.CharField(label="Nombre de Usuario")
    email=forms.EmailField(label="Correo Electrónico")
    password1=forms.CharField(label="Contraseña",widget=forms.PasswordInput)
    password2=forms.CharField(label="Repetir contraseña",widget=forms.PasswordInput)
    first_name=forms.CharField(label="Nombre")
    last_name=forms.CharField(label="Apellido")
    
    class Meta:
        model=User
        fields=["username","email","password1","password2","first_name","last_name"]
        help_text={key:"" for key in fields}


class FormularioModificarContrasenia(PasswordChangeForm):
    old_password=forms.CharField(label="Contraseña actual",widget=forms.PasswordInput)
    new_password1=forms.CharField(label="Contraseña nueva",widget=forms.PasswordInput)
    new_password2=forms.CharField(label="Repetir contraseña nueva",widget=forms.PasswordInput)
    
    class Meta:
        model=User
        fields=["old_password","new_password1","new_password2"]
        help_text={
            "old_password": "",
            "new_password1": "",
            "new_password2": "",
        }
        

class FormularioModificarPerfil(UserChangeForm):
    email=forms.EmailField(required=True)
    first_name=forms.CharField(label="Nombre")
    last_name=forms.CharField(label="Apellido")
    password=None
    avatar=forms.ImageField(required=False,label="Avatar")
    fecha_de_nacimiento=forms.DateField(
        widget=forms.DateInput(attrs={"type":"date"}),
        required=False, 
        label="Fecha de Nacimiento")
    
    class Meta:
        model=User
        fields=["email","first_name","last_name","fecha_de_nacimiento","avatar"]
        help_text={key:"" for key in fields}
        
# class FormularioVerPefil(forms.ModelForm):
#     username=forms.CharField(label="Nombre de usuario")
#     email=forms.EmailField(label= "Correo Electrónico")
#     first_name=forms.CharField(label="Nombre")
#     last_name=forms.CharField(label="Apellido")
#     fecha_de_nacimiento=forms.DateField(
#         widget=forms.DateInput(attrs={"type":"date"}),
#         required=False, 
#         label="Fecha de Nacimiento")
#     avatar=forms.ImageField(required=False, label="Avatar")
    
#     class Meta:
#         model=User
#         fields=["username","email","first_name","last_name","fecha_de_nacimiento","avatar"]
#         help_text={key:"" for key in fields}
        
    
    

usuarios/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm,UserChangeForm
from django.contrib.auth import authenticate,login
from usuarios.forms import FormularioDeRegistro,FormularioModificarPerfil,FormularioModificarContrasenia
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from usuarios.models import DatosExtra

def acceso(request):
    formulario=AuthenticationForm()
    if request.method == "POST":
        formulario=AuthenticationForm(request,data=request.POST)
        if formulario.is_valid():
            nombre_usuario=formulario.cleaned_data.get("username")
            contrasenia=formulario.cleaned_data.get("password")
            usuario=authenticate(username=nombre_usuario,password=contrasenia)
            
            login(request,usuario)
            DatosExtra.objects.get_or_create(user=usuario)
            return redirect("usuarios:ver_perfil")
        
    
    return render(request,"usuarios/acceso.html",{"form":formulario})

def registro(request):
    formulario=FormularioDeRegistro()
    if request.method=="POST":
        formulario=FormularioDeRegistro(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect("usuarios:acceso")
    return render(request,"usuarios/registro.html",{"form":formulario})

@login_required
def modificar_perfil(request):
    datos_extra=request.user.datosextra
    formulario=FormularioModificarPerfil(instance=request.user,initial={"avatar":datos_extra.avatar,"fecha_de_nacimiento": datos_extra.fecha_de_nacimiento})
    if request.method=="POST":
        formulario=FormularioModificarPerfil(request.POST,request.FILES,instance=request.user)
        if formulario.is_valid():
            new_avatar=formulario.cleaned_data.get("avatar")
            new_fecha_de_nacimiento = formulario.cleaned_data.get("fecha_de_nacimiento")
            datos_extra.avatar=new_avatar if new_avatar else datos_extra.avatar
            datos_extra.fecha_de_nacimiento = new_fecha_de_nacimiento if new_fecha_de_nacimiento else datos_extra.fecha_de_nacimiento
            datos_extra.save()
            formulario.save()
            return redirect("usuarios:ver_perfil")
    return render(request,"usuarios/modificar_perfil.html",{"form":formulario})

class ModificarContrasenia(LoginRequiredMixin,PasswordChangeView):
    form_class=FormularioModificarContrasenia
    template_name="usuarios/modificar_contrasenia.html"
    success_url=reverse_lazy("usuarios:modificar_perfil")
    
@login_required
def ver_perfil(request):
    usuario=request.user
    datos_extra,created=DatosExtra.objects.get_or_create(user=usuario)
    return render(request,"usuarios/ver_perfil.html",{"usuario": usuario,"datos_extra":datos_extra})

usuarios/templates/usuarios/acceso.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Ingresar a la página
{% endblock title_head %}

{% block h1_header %}
Ingresar a la página
{% endblock h1_header %}

{% block main %}


<form action={% url "usuarios:acceso" %} method="post">  
    {% csrf_token %}
    <table>
        {{form}}  

    </table>
    <input type="submit" value="Ingresar a la página">
</form>

{% endblock main %}

usuarios/templates/usuarios/modificar_contrasenia.html
{% extends "base.html" %}

{% load static %}
{% block title_head %}
Modificar contraseña
{% endblock title_head %}

{% block h1_header %}
Modificar contraseña de {{request.user.username}}
{% endblock h1_header %}

{% block main %}


<form action={% url "usuarios:modificar_contrasenia" %} method="post">  
    {% csrf_token %}
    <table>
        {{form}}  

    </table>
    <input type="submit" value="Modificar">
</form>

{% endblock main %}

usuarios/templates/usuarios/modificar_perfil.html
{% extends "base.html" %}

{% load static %}
{% block title_head %}
Modificar el perfil
{% endblock title_head %}

{% block h1_header %}
Modificar el perfil de {{request.user.username}}
{% endblock h1_header %}

{% block main %}


<form action={% url "usuarios:modificar_perfil" %} method="post" enctype="multipart/form-data">  
    {% csrf_token %}
    <table>
        {{form}}  

    </table>
    <input type="submit" value="Modificar">
</form>

<div class="navbar">
    <a href={% url "usuarios:modificar_contrasenia" %} class="btn btn-danger">Modificar contraseña</a>

</div>

{% endblock main %}

usuarios/templates/usuarios/registro.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Registro
{% endblock title_head %}

{% block h1_header %}
Registarse en la página
{% endblock h1_header %}

{% block main %}


<form action={% url "usuarios:registro" %} method="post">  
    {% csrf_token %}
    <table>

        {{form}}  
    </table>
    <input type="submit" value="Registrarse">
</form>

{% endblock main %}

usuarios/templates/usuarios/salir.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Cerrar Sesión
{% endblock title_head %}

{% block h1_header %}
Se cerró la Sesión
{% endblock h1_header %}

{% block main %}

{% endblock main %}

usuarios/templates/usuarios/ver_perfil.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Perfil completo 
{% endblock title_head %}

{% block h1_header %}
Perfil completo de {{usuario.username}}
{% endblock h1_header %}

{% block main %}

<ul>

    <li>Nombre: {{ usuario.first_name }}</li>
    <li>Apellido:{{ usuario.last_name }}</li>
    <li>Email: {{ usuario.email }}</li>
    <li>Nombre de usuario:{{ usuario.username }}</li>
    
    {% if datos_extra.fecha_de_nacimiento %}
    
    <li>Fecha de Nacimiento:{{ datos_extra.fecha_de_nacimiento }}</li>
    {% else %}
    <li>Fecha de Nacimiento: No hay una fecha cargada</li> 
    {% endif %}
    
    
        {% if datos_extra.avatar %}
        <li>Avatar: <img src="{{datos_extra.avatar.url }}" alt="Avatar" height= "100px"></li>
        {% else %}
        <li>No hay avatar disponible</li>
        
        
        {% endif %}
        
</ul>
    
<a href="{% url 'usuarios:modificar_perfil' %}" class="btn btn-info">Modificar perfil</a>
<a href="{% url 'comienzo:inicio' %}" class="btn btn-success">Ir a inicio</a>
<div class="navbar">
    <a href={% url "usuarios:modificar_contrasenia" %} class="btn btn-danger">Modificar contraseña</a>

</div>

{% endblock main %}